import numpy as np

def BZ_to_1BZ(kpts):
    """
    Map k-points to the first Brillouin zone.
    kpts: (nkpts, 3) array of k-points in fractional coordinates
    """
    kpts = np.where(np.abs(kpts - 0.5) < 1e-8, 0.5 - 1e-12, kpts)
    kpts = np.where(np.abs(kpts + 0.5) < 1e-8, -0.5 - 1e-12, kpts)
    kpts = np.floor(0.5 - kpts) + kpts
    return kpts

def find_translated_index_batched(kpts, q_vec, tol=1e-6):
    """
    Find the index of the k-point that is translated by trs_vector for the whole k point lists
    kpts: (nkpts, 3) array of k-points in fractional coordinates
    trs_vector: (3,) array of the translation vector in fractional coordinates
    """
    # assert np.max(np.abs(kpts)) < 0.5
    # here we do not do sanity check, make sure the kpts are in the first BZ
    idxlis = []
    kpts_translated = kpts + q_vec
    fbz_kpts_trs = BZ_to_1BZ(kpts_translated)
    # print(fbz_kpts_trs)

    for i in range(fbz_kpts_trs.shape[0]):
        kpt = fbz_kpts_trs[i]
        for j in range(len(kpts)):
            if np.allclose(kpt, kpts[j], atol=tol):
                idxlis.append(j)
    idxlis = np.array(idxlis, dtype=np.int64)
    return idxlis

def construct_kpq(kpts_frac):
    nk = kpts_frac.shape[0]
    idx_kpq_mat = np.zeros((nk, nk), dtype=np.int64)
    for iq in range(nk):
        qvec = kpts_frac[iq]
        idx_kpq = find_translated_index_batched(kpts_frac, qvec)
        idx_kpq_mat[iq] = idx_kpq
    return idx_kpq_mat

def find_inverted_index_batched(kpts, tol=1e-6):
    """
    Find the index of the k-point that is transformed to -k for
    kpts: (nkpts, 3) array of k-points in fractional coordinates
    trs_vector: (3,) array of the translation vector in fractional coordinates
    """
    # assert np.max(np.abs(kpts)) < 0.5
    # here we do not do sanity check, make sure the kpts are in the first BZ
    idxlis = []
    mkpts = -kpts
    fbz_mkpts = BZ_to_1BZ(mkpts)
    for i in range(fbz_mkpts.shape[0]):
        fbz_mkpt = fbz_mkpts[i]
        for j in range(len(kpts)):
            if np.allclose(fbz_mkpt, kpts[j], atol=tol):
                idxlis.append(j)
    idxlis = np.array(idxlis, dtype=np.int64)
    return idxlis


def generate_MPmesh_3d(meshsize):
    """
    Generate the Monkhorst-Pack mesh
    For MP mesh, the k points are generated by the formula:
    k_i = (n_i + (1-N_i)/2) / N_i
    meshsize: tuple of 3 integers
    """
    N1, N2, N3 = meshsize
    kpts = []
    for n1 in range(N1):
        for n2 in range(N2):
            for n3 in range(N3):
                kpt = np.array([(n1 + 0.5 * (1 - N1)) / N1, (n2 + 0.5 * (1 - N2)) / N2, (n3 + 0.5 * (1 - N3)) / N3])
                kpts.append(kpt)
    
    kpts = np.array(kpts)
    
    # check if gamma point is in the mesh
    gamma = np.array([0.0, 0.0, 0.0])
    if not any(np.allclose(kpt, gamma) for kpt in kpts):
        kpts -= kpts[0]
        kpts = BZ_to_1BZ(kpts)
    return kpts

kpts_frac = generate_MPmesh_3d([3, 1, 1])
mk = find_inverted_index_batched(kpts_frac)
kpq = construct_kpq(kpts_frac)

nchol = 200
nbsf = 26
nelec = 4
nk = kpts_frac.shape[0]

chol = np.random.rand(nk, nchol, nk, nbsf, nbsf) + 1j * np.random.rand(nk, nchol, nk, nbsf, nbsf) # q, gamma, k, mu, nu

chol_new = np.zeros_like(chol)

for iq in range(nk):
    if mk[iq] >= iq:
        chol_new[iq] = chol[iq]
    else:
        for ik in range(nk):
            chol_new[iq, :, ik] = chol[mk[iq], :, kpq[iq, ik]].transpose(0, 2, 1).conj()


for iq in range(nk):
    if mk[iq] != iq:
        for ik in range(nk):
            assert np.allclose(chol_new[iq, :, ik], chol_new[mk[iq], :, kpq[iq, ik]].transpose(0, 2, 1).conj())
