name: CI

on: [pull_request]

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: openmpi 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install -r dev/dev.txt
      - name: pylint
        run: |
          python dev/run_tests.py --pylint
      - name: format
        run: |
          python dev/run_tests.py --black
      - name: flynt
        run: |
          python dev/run_tests.py --flynt
  build:
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
        mpi:
          - openmpi
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev/dev.txt
        pip install pyblock
        pip install pyscf
    - name: Install package
      run: |
        # HACK FOR LEGACY CODE!
        export BUILD_LEGACY_IPIE=1; python -m pip install -e .
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-xdist
        python -m pytest -n=auto
    - name: mpi test
      run: |
        mpiexec -n 2 python -m pytest ipie/legacy/walkers/tests/test_handler.py
        mpiexec -n 6 python -m pytest ipie/estimators/tests/test_generic_chunked.py
        mpiexec -n 6 python -m pytest ipie/propagation/tests/test_generic_chunked.py
    - name: Test Integration
      timeout-minutes: 10
      run: |
        mpirun -np 4 python -u ipie/qmc/tests/test_mpi_integration.py
        python dev/run_tests.py --examples
    - name: No mpi4py
      run: |
        pip uninstall mpi4py
        python -c "from ipie.config import MPI; assert \"FakeComm\" in str(MPI.COMM_WORLD)"
        python -m pytest -n=auto
    # - name: Codecov
    #   uses: codecov/codecov-action@v3.1.1

